---
title: "Texas Blackouts Winter Storm Uri, February, 2021"
author: "Henry Oliver"
format: html
---

1) Load packages and data
```{r}
#| message: false
library(tidyverse)
library(janitor)
library(sf) # vector handling
library(terra) # raster handling
library(tidyverse)
library(tmap) # map making
library(spData) # spatial data
library(spDataLarge) # spatial data
library(viridisLite)
library(stars)
library(raster)
```


## Import data
```{r}
#| message: false
# nightlight data for February 7, tile h08v05
nl_feb7_05 <- read_stars("data/VNP46A1/VNP46A1.A2021038.h08v05.001.2021039064328.tif")

# nightlight data for February 7, tile h08v06
nl_feb7_06 <- read_stars("data/VNP46A1/VNP46A1.A2021038.h08v06.001.2021039064329.tif")

# nightlight data for February 16, tile h08v05
nl_feb16_05 <- read_stars("data/VNP46A1/VNP46A1.A2021047.h08v05.001.2021048091106.tif")

# nightlight data for February 16, tile h08v06
nl_feb16_06 <- read_stars("data/VNP46A1/VNP46A1.A2021047.h08v06.001.2021048091105.tif")


```

## Check dimensions, resolution, and CRS
```{r}
# Check dimensions
if (all(dim(nl_feb7_06) == dim(nl_feb16_05)) && 
    all(dim(nl_feb7_06) == dim(nl_feb16_06)) &&
    all(dim(nl_feb7_06) == dim(nl_feb7_05))) {
  message("All rasters have the same dimensions")
} else {
  message("Rasters do not have the same dimensions")
}

# Check resolution
if (all(st_res(nl_feb7_06) == st_res(nl_feb16_05)) && 
    all(st_res(nl_feb7_06) == st_res(nl_feb16_06)) &&
    all(st_res(nl_feb7_06) == st_res(nl_feb7_05))) {
  message("All rasters have the same resolution")
} else {
  message("Rasters do not have the same resolution")
}

# Compare CRS of rasters
rasters <- list(nl_feb7_05, nl_feb7_06, nl_feb16_05, nl_feb16_06)

crs_match <- all(sapply(rasters[-1], function(x) compareCRS(rasters[[1]], x)))

if (crs_match) {
  message ("All Rasters have the same CRS")
} else {
  message("All Rasters do NOT have the same CRS")
}
```

## Create blackout mask
```{r}
#| warning: false
# merge rasters
nl_feb7 = st_mosaic(nl_feb7_05, nl_feb7_06)
nl_feb16 = st_mosaic(nl_feb16_05, nl_feb16_06)

# Find the difference between the two rasters for both tiles
nl_diff <- (nl_feb7 - nl_feb16)

# Create reclassification matrix
source("class_function.R")

# Apply reclassification function
diff_rcf <- st_apply(nl_diff, MARGIN = c(1, 2), FUN = function(x) reclassify(x, threshold = 200))

# Transform into vector for ease of merging with census data
mask_vector = st_as_sf(diff_rcf)

# Crop mask to City of Houston
bounds <- st_bbox(c(xmin = -96.5, ymin = 29, xmax = -94.5, ymax = 30.5))
houston_mask <- st_crop(mask_vector, bounds)

```






